import { getProductImages } from './images';

const imgs = (slug) => getProductImages(slug);

export const ALL_PRODUCTS = [
  {
    id: 'luminous-face-oil',
    slug: 'luminous-face-oil',
    name: 'Luminous Face Oil',
    subtitle: 'Revitalizing Glow',
    price: 55,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: true,
    isNew: false,
    bgColor: '#E8E4E0',
    image: imgs('luminous-face-oil').main,
    images: imgs('luminous-face-oil').gallery,
    editorialImage: imgs('luminous-face-oil').editorial,
    size: '30ml',
    description: 'A lightweight, fast-absorbing face oil enriched with rosehip and jojoba to restore luminosity and soften fine lines.',
    ingredients: ['Rosehip Oil', 'Jojoba', 'Vitamin E', 'Squalane'],
    benefits: [
      { title: 'Glows', description: 'Instant radiance without greasiness' },
      { title: 'Nourishes', description: 'Deeply conditions dry, tired skin' },
      { title: 'Protects', description: 'Antioxidant-rich daily defense' },
    ],
    spotlight: 'Rosehip oil delivers essential fatty acids for a naturally luminous complexion.',
  },
  {
    id: 'radiance-serum',
    slug: 'radiance-serum',
    name: 'Radiance Serum',
    subtitle: 'Brightening Vitamin C Complex',
    price: 76,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: true,
    isNew: false,
    bgColor: '#C4785A',
    image: imgs('radiance-serum').main,
    images: imgs('radiance-serum').gallery,
    editorialImage: imgs('radiance-serum').editorial,
    size: '30ml',
    description: 'A luminous, fast-absorbing serum with stabilized Vitamin C and niacinamide to visibly brighten and even tone.',
    ingredients: ['Vitamin C', 'Niacinamide', 'Hyaluronic Acid', 'Rosehip Oil'],
    benefits: [
      { title: 'Brightens', description: 'Visibly reduces dullness and dark spots' },
      { title: 'Hydrates', description: 'Deep moisture without heaviness' },
      { title: 'Protects', description: 'Antioxidant shield against stress' },
    ],
    spotlight: 'Stabilized Vitamin C for lasting luminosity from the first application.',
  },
  {
    id: 'hydra-rich-moisturizer',
    slug: 'hydra-rich-moisturizer',
    name: 'Hydra-Rich Moisturizer',
    subtitle: 'Deep Hydration',
    price: 48,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: true,
    isNew: false,
    bgColor: '#3D2B1F',
    image: imgs('hydra-rich-moisturizer').main,
    images: imgs('hydra-rich-moisturizer').gallery,
    editorialImage: imgs('hydra-rich-moisturizer').editorial,
    size: '50ml',
    description: 'A rich yet weightless cream that locks in moisture for up to 24 hours with ceramides and hyaluronic acid.',
    ingredients: ['Ceramides', 'Hyaluronic Acid', 'Shea Butter', 'Peptides'],
    benefits: [
      { title: 'Hydrates', description: '24-hour moisture barrier support' },
      { title: 'Repairs', description: 'Strengthens skin\'s natural barrier' },
      { title: 'Plumps', description: 'Smoother, firmer-looking skin' },
    ],
    spotlight: 'Ceramide complex rebuilds moisture reserves for lasting comfort.',
  },
  {
    id: 'velvet-lip-tint',
    slug: 'velvet-lip-tint',
    name: 'Velvet Lip Tint',
    subtitle: 'Lasting Color',
    price: 28,
    category: 'makeup',
    brand: 'KN Color',
    isBestSeller: true,
    isNew: false,
    bgColor: '#8B9A7E',
    image: imgs('velvet-lip-tint').main,
    images: imgs('velvet-lip-tint').gallery,
    editorialImage: imgs('velvet-lip-tint').editorial,
    size: '5ml',
    description: 'A weightless lip tint with a soft matte finish that lasts all day without drying.',
    ingredients: ['Jojoba Oil', 'Vitamin E', 'Natural Pigments'],
    benefits: [
      { title: 'Lasts', description: 'Transfer-resistant all-day color' },
      { title: 'Comforts', description: 'Never dry or cracking' },
      { title: 'Flatters', description: 'Buildable, natural finish' },
    ],
    spotlight: 'Botanical oils keep lips soft while color stays true for hours.',
  },
  {
    id: 'silk-cleansing-balm',
    slug: 'silk-cleansing-balm',
    name: 'Silk Cleansing Balm',
    subtitle: 'Gentle First Cleanse',
    price: 42,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: false,
    isNew: true,
    bgColor: '#F0EDE9',
    image: imgs('silk-cleansing-balm').main,
    images: imgs('silk-cleansing-balm').gallery,
    editorialImage: imgs('silk-cleansing-balm').editorial,
    size: '100ml',
    description: 'A buttery balm that melts away makeup and impurities while leaving skin silky-soft.',
    ingredients: ['Camellia Oil', 'Chamomile', 'Vitamin E'],
    benefits: [
      { title: 'Melts', description: 'Dissolves makeup effortlessly' },
      { title: 'Soothes', description: 'Calms sensitive skin' },
      { title: 'Softens', description: 'Silky, never stripped feeling' },
    ],
    spotlight: 'Camellia oil transforms from balm to silk upon contact with skin.',
  },
  {
    id: 'golden-eye-cream',
    slug: 'golden-eye-cream',
    name: 'Golden Eye Cream',
    subtitle: 'Depuff & Illuminate',
    price: 62,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: false,
    isNew: true,
    bgColor: '#CFA670',
    image: imgs('golden-eye-cream').main,
    images: imgs('golden-eye-cream').gallery,
    editorialImage: imgs('golden-eye-cream').editorial,
    size: '15ml',
    description: 'A luxurious eye cream with gold peptides to reduce puffiness and brighten dark circles.',
    ingredients: ['Gold Peptides', 'Caffeine', 'Hyaluronic Acid'],
    benefits: [
      { title: 'Depuffs', description: 'Reduces morning under-eye swelling' },
      { title: 'Brightens', description: 'Illuminates dark circles' },
      { title: 'Firms', description: 'Smoother, tighter eye area' },
    ],
    spotlight: 'Gold peptides energize delicate skin for a rested, luminous look.',
  },
  {
    id: 'rosewater-toner',
    slug: 'rosewater-toner',
    name: 'Rosewater Toner',
    subtitle: 'Balancing Mist',
    price: 34,
    category: 'skincare',
    brand: 'KN Essentials',
    isBestSeller: false,
    isNew: true,
    bgColor: '#E8C4C8',
    image: imgs('rosewater-toner').main,
    images: imgs('rosewater-toner').gallery,
    editorialImage: imgs('rosewater-toner').editorial,
    size: '150ml',
    description: 'A refreshing rosewater toner that balances pH and preps skin for optimal absorption.',
    ingredients: ['Rosewater', 'Glycerin', 'Aloe Vera'],
    benefits: [
      { title: 'Balances', description: 'Restores optimal skin pH' },
      { title: 'Refreshes', description: 'Instant cooling hydration' },
      { title: 'Preps', description: 'Maximizes serum absorption' },
    ],
    spotlight: 'Bulgarian rosewater soothes and preps skin in one delicate mist.',
  },
  {
    id: 'luminous-foundation',
    slug: 'luminous-foundation',
    name: 'Luminous Foundation',
    subtitle: 'Second-Skin Finish',
    price: 52,
    category: 'makeup',
    brand: 'KN Color',
    isBestSeller: false,
    isNew: true,
    bgColor: '#D4C4B0',
    image: imgs('luminous-foundation').main,
    images: imgs('luminous-foundation').gallery,
    editorialImage: imgs('luminous-foundation').editorial,
    size: '30ml',
    description: 'A buildable foundation with light-reflecting pigments for a dewy, second-skin finish.',
    ingredients: ['Light-Reflecting Pigments', 'Hyaluronic Acid', 'SPF 15'],
    benefits: [
      { title: 'Glows', description: 'Natural luminosity, never cakey' },
      { title: 'Covers', description: 'Buildable medium coverage' },
      { title: 'Protects', description: 'Built-in SPF 15' },
    ],
    spotlight: 'Light-reflecting pigments mimic natural skin radiance.',
  },
  {
    id: 'cashmere-blush',
    slug: 'cashmere-blush',
    name: 'Cashmere Blush',
    subtitle: 'Soft Flush',
    price: 36,
    category: 'makeup',
    brand: 'KN Color',
    isBestSeller: false,
    isNew: true,
    bgColor: '#E8C4C8',
    image: imgs('cashmere-blush').main,
    images: imgs('cashmere-blush').gallery,
    editorialImage: imgs('cashmere-blush').editorial,
    size: '6g',
    description: 'A finely milled blush with a cashmere-soft texture for a natural, lit-from-within flush.',
    ingredients: ['Silica', 'Vitamin E', 'Natural Pigments'],
    benefits: [
      { title: 'Blends', description: 'Seamless, streak-free application' },
      { title: 'Lasts', description: 'All-day natural color' },
      { title: 'Flatters', description: 'Universally flattering shades' },
    ],
    spotlight: 'Silica micro-spheres create an airbrushed, cashmere-soft finish.',
  },
  {
    id: 'velvet-mascara',
    slug: 'velvet-mascara',
    name: 'Velvet Mascara',
    subtitle: 'Volume & Length',
    price: 32,
    category: 'makeup',
    brand: 'KN Color',
    isBestSeller: false,
    isNew: false,
    bgColor: '#222222',
    image: imgs('velvet-mascara').main,
    images: imgs('velvet-mascara').gallery,
    editorialImage: imgs('velvet-mascara').editorial,
    size: '8ml',
    description: 'A volumizing mascara with a velvety black finish — no clumps, all drama.',
    ingredients: ['Beeswax', 'Carnauba Wax', 'Vitamin B5'],
    benefits: [
      { title: 'Volumizes', description: 'Dramatic lash fullness' },
      { title: 'Lengthens', description: 'Visible extension effect' },
      { title: 'Conditions', description: 'Nourishes lash health' },
    ],
    spotlight: 'Dual-bristle brush coats every lash for velvet-black volume.',
  },
  {
    id: 'amber-oud-perfume',
    slug: 'amber-oud-perfume',
    name: 'Amber Oud Parfum',
    subtitle: 'Warm & Enigmatic',
    price: 128,
    category: 'fragrance',
    brand: 'KN Atelier',
    isBestSeller: false,
    isNew: true,
    bgColor: '#3D2B1F',
    image: imgs('amber-oud-perfume').main,
    images: imgs('amber-oud-perfume').gallery,
    editorialImage: imgs('amber-oud-perfume').editorial,
    size: '50ml',
    description: 'An opulent blend of amber, oud, and saffron — warm, mysterious, and unforgettable.',
    ingredients: ['Amber', 'Oud', 'Saffron', 'Sandalwood'],
    benefits: [
      { title: 'Lasts', description: '8+ hours on skin' },
      { title: 'Evokes', description: 'Warm, sophisticated aura' },
      { title: 'Layers', description: 'Pairs beautifully with body oil' },
    ],
    spotlight: 'Rare oud and saffron create a signature scent unlike any other.',
  },
  {
    id: 'bare-lip-gloss',
    slug: 'bare-lip-gloss',
    name: 'Bare Lip Gloss',
    subtitle: 'Sheer Shine',
    price: 24,
    category: 'makeup',
    brand: 'KN Color',
    isBestSeller: false,
    isNew: true,
    bgColor: '#F0EDE9',
    image: imgs('bare-lip-gloss').main,
    images: imgs('bare-lip-gloss').gallery,
    editorialImage: imgs('bare-lip-gloss').editorial,
    size: '8ml',
    description: 'A non-sticky gloss with sheer shine and a hint of color for effortless everyday glamour.',
    ingredients: ['Jojoba Oil', 'Vitamin E', 'Light Pigments'],
    benefits: [
      { title: 'Shines', description: 'High-gloss without stickiness' },
      { title: 'Hydrates', description: 'Plump, comfortable lips' },
      { title: 'Enhances', description: 'Your natural lip color, elevated' },
    ],
    spotlight: 'Jojoba oil delivers cushiony comfort with mirror-like shine.',
  },
];

export const getProductBySlug = (slug) =>
  ALL_PRODUCTS.find((p) => p.slug === slug) ?? null;

export const getProductsByCategory = (category) =>
  ALL_PRODUCTS.filter((p) => p.category === category);

export const BEST_SELLERS = ALL_PRODUCTS.filter((p) => p.isBestSeller);

export const NEW_ARRIVALS = ALL_PRODUCTS.filter((p) => p.isNew);

export const BRANDS = [
  { id: 'kn-essentials', name: 'KN Essentials', tagline: 'Skincare Rituals', image: imgs('radiance-serum').main, href: '/shop?brand=kn-essentials' },
  { id: 'kn-color', name: 'KN Color', tagline: 'Modern Makeup', image: imgs('luminous-foundation').main, href: '/shop?brand=kn-color' },
  { id: 'kn-atelier', name: 'KN Atelier', tagline: 'Fine Fragrance', image: imgs('amber-oud-perfume').main, href: '/shop?brand=kn-atelier' },
  { id: 'la-merve', name: 'La Merve', tagline: 'Luxury Skincare', image: imgs('golden-eye-cream').main, href: '/shop?brand=la-merve' },
  { id: 'noir-parfum', name: 'Noir Parfum', tagline: 'Artisan Scents', image: imgs('amber-oud-perfume').gallery[1], href: '/shop?brand=noir-parfum' },
  { id: 'pure-glow', name: 'Pure Glow', tagline: 'Clean Beauty', image: imgs('bare-lip-gloss').main, href: '/shop?brand=pure-glow' },
];

export const RADIANCE_SERUM = getProductBySlug('radiance-serum');
